apiVersion: batch/v1
kind: Job
metadata:
  name: "cpmg-gatling-performance-tests"
spec:
  template:
    spec:
      containers:
      - name: "cpmg-gatling-performance-tests"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      restartPolicy: Never
  backoffLimit: 1
