version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@2.2
  
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
      - request-preprod-debug-approval:
          type: approval
          requires:
            - helm_lint
            - build_docker
      - hmpps/deploy_env:
          name: run_perf_debug
          retrieve_secrets: none
          env: "preprod"
          context: court-probation-preprod
          slack_notification: true
          slack_channel_name: probation_in_court_dev
          helm_additional_args: "--set PERF_TEST_USERS=1 --set PERF_TEST_DURATION=1>"
          requires: 
            - request-preprod-debug-approval
      - request-preprod-2-approval:
          type: approval
          requires:
            - helm_lint
            - build_docker
      - hmpps/deploy_env:
          name: run_perf_2
          retrieve_secrets: none
          env: "preprod"
          context: court-probation-preprod
          slack_notification: true
          slack_channel_name: probation_in_court_dev
          helm_additional_args: "--set PERF_TEST_USERS=2 --set PERF_TEST_DURATION=2>"
          requires: 
            - request-preprod-2-approval
      - request-preprod-10k-approval:
          type: approval
          requires:
            - helm_lint
            - build_docker
      - hmpps/deploy_env:
          name: run_perf_10k
          retrieve_secrets: none
          env: "preprod"
          context: court-probation-preprod
          slack_notification: true
          slack_channel_name: probation_in_court_dev
          helm_additional_args: "--set PERF_TEST_USERS=10000 --set PERF_TEST_DURATION=10>"
          requires: 
            - request-preprod-10k-approval
      - request-preprod-5k-approval:
          type: approval
          requires:
            - helm_lint
            - build_docker
      - hmpps/deploy_env:
          name: run_perf_5k
          retrieve_secrets: none
          env: "preprod"
          context: court-probation-preprod
          slack_notification: true
          slack_channel_name: probation_in_court_dev
          helm_additional_args: "--set PERF_TEST_USERS=5000 --set PERF_TEST_DURATION=10>"
          requires: 
            - request-preprod-5k-approval
      - request-preprod-2k-approval:
          type: approval
          requires:
            - helm_lint
            - build_docker
      - hmpps/deploy_env:
          name: run_perf_2k
          retrieve_secrets: none
          env: "preprod"
          context: court-probation-preprod
          slack_notification: true
          slack_channel_name: probation_in_court_dev
          helm_additional_args: "--set PERF_TEST_USERS=2000 --set PERF_TEST_DURATION=10>"
          requires: 
            - request-preprod-2k-approval
      - request-preprod-1k-approval:
          type: approval
          requires:
            - helm_lint
            - build_docker
      - hmpps/deploy_env:
          name: run_perf_1k
          retrieve_secrets: none
          env: "preprod"
          context: court-probation-preprod
          slack_notification: true
          slack_channel_name: probation_in_court_dev
          helm_additional_args: "--set PERF_TEST_USERS=1000 --set PERF_TEST_DURATION=10>"
          requires: 
            - request-preprod-1k-approval
