version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@2.2

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
      - request-preprod-approval:
          type: approval
          requires:
            - helm_lint
            - build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_preprod
          retrieve_secrets: none
          env: "preprod"
          context: court-probation-preprod
          requires:
            - request-preprod-approval